language: julia
os:
    - osx
    - linux
    - windows
julia:
    - 1
    - nightly
matrix:
    allow_failures:
        - julia: nightly
notifications:
    email: false
after_success:
    - julia --color=yes -e 'import Pkg; import IonSim; cd(joinpath(dirname(pathof(IonSim)), "..")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
